/* Generated By:JavaCC: Do not edit this line. GrammarConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface GrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_INT = 8;
  /** RegularExpression Id. */
  int T_STRING = 9;
  /** RegularExpression Id. */
  int T_BOOLEAN = 10;
  /** RegularExpression Id. */
  int T_IF = 11;
  /** RegularExpression Id. */
  int T_ELSE = 12;
  /** RegularExpression Id. */
  int T_WHILE = 13;
  /** RegularExpression Id. */
  int T_THIS = 14;
  /** RegularExpression Id. */
  int T_NEW = 15;
  /** RegularExpression Id. */
  int T_PUBLIC = 16;
  /** RegularExpression Id. */
  int T_STATIC = 17;
  /** RegularExpression Id. */
  int T_VOID = 18;
  /** RegularExpression Id. */
  int T_CLASS = 19;
  /** RegularExpression Id. */
  int T_EXTENDS = 20;
  /** RegularExpression Id. */
  int T_RETURN = 21;
  /** RegularExpression Id. */
  int T_MAIN = 22;
  /** RegularExpression Id. */
  int T_LENGTH = 23;
  /** RegularExpression Id. */
  int T_SYSTEM = 24;
  /** RegularExpression Id. */
  int T_OUT = 25;
  /** RegularExpression Id. */
  int T_PRINTLN = 26;
  /** RegularExpression Id. */
  int T_TRUE = 27;
  /** RegularExpression Id. */
  int T_FALSE = 28;
  /** RegularExpression Id. */
  int T_OP_BIN = 29;
  /** RegularExpression Id. */
  int T_OP_UN = 30;
  /** RegularExpression Id. */
  int T_LPAR = 31;
  /** RegularExpression Id. */
  int T_RPAR = 32;
  /** RegularExpression Id. */
  int T_LCOL = 33;
  /** RegularExpression Id. */
  int T_RCOL = 34;
  /** RegularExpression Id. */
  int T_LCHAVE = 35;
  /** RegularExpression Id. */
  int T_RCHAVE = 36;
  /** RegularExpression Id. */
  int T_PVIRGULA = 37;
  /** RegularExpression Id. */
  int T_VIRGULA = 38;
  /** RegularExpression Id. */
  int T_DOT = 39;
  /** RegularExpression Id. */
  int T_ASSIGN = 40;
  /** RegularExpression Id. */
  int DIGIT = 41;
  /** RegularExpression Id. */
  int T_ID = 42;
  /** RegularExpression Id. */
  int T_INTEGER_LITERAL = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "\"int\"",
    "\"String\"",
    "\"boolean\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"this\"",
    "\"new\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"class\"",
    "\"extends\"",
    "\"return\"",
    "\"main\"",
    "\"length\"",
    "\"System\"",
    "\"out\"",
    "\"println\"",
    "\"true\"",
    "\"false\"",
    "<T_OP_BIN>",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "<DIGIT>",
    "<T_ID>",
    "<T_INTEGER_LITERAL>",
  };

}
